### PR TITLE
change ansible version to 2.1.1.0

### PR DESCRIPTION
**Pull request by kenthua**

### CODE REVIEW

**Comment by sherl0cks** [comment]
@kenthua this is related to some of this CI infra, lemme look into this quickly for you

**Comment by kenthua** [comment]
@sherl0cks having problems pulling the bpm deployable binary in the travis test

**Comment by sherl0cks** [comment]
@kenthua yea - that's the infra issue... working on it, but there are few other priorities we gotta work through first

**Comment by sherl0cks** [comment]
Merging this and then fixing CI in later PR

**Pull request merged**
